version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase
  labels:
    - "dependencies"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
