version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase
  labels:
    - "dependencies"
  allow:
    - dependency-type: "all"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
