---
name: CI

"on": [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - id: tox-env
        run: |
          VERSION=${{ matrix.python-version }}
          echo "environment=${VERSION//.}" >> $GITHUB_OUTPUT
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: llvm/lib/libclang.so*
          key: llvm-21
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: sudo ln -s ${{ env.LLVM_PATH }}/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-21.so
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.3"
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
      - name: Test with tox
        run: |
          uv run --locked tox -e py${{ steps.tox-env.outputs.environment }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: llvm/lib/libclang.so*
          key: llvm-21
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: sudo ln -s ${{ env.LLVM_PATH }}/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-21.so
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.3"
          enable-cache: true
          cache-suffix: "coverage"
      - name: Test with tox
        run: |
          uv run --locked tox -e cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
          fail_ci_if_error: true

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ["pylint", "pycodestyle", "black", "mypy"]
    steps:
      - uses: actions/checkout@v7
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: llvm/lib/libclang.so*
          key: llvm-21
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: sudo ln -s ${{ env.LLVM_PATH }}/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-21.so
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.3"
          enable-cache: true
          cache-suffix: "check"
      - name: Static code checks
        run: |
          uv run --locked tox -e check-${{ matrix.check }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: llvm/lib/libclang.so*
          key: llvm-21
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: sudo ln -s ${{ env.LLVM_PATH }}/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-21.so
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.3"
          enable-cache: true
          cache-suffix: "docs"
      - name: Build docs
        run: |
          uv run --locked tox -e docs
  sphinx:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sphinx-version: ["four"]
    steps:
      - uses: actions/checkout@v7
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: llvm/lib/libclang.so*
          key: llvm-12
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "12.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Symlink libclang.so
        run: |
          sudo ln -s ${{ env.LLVM_PATH }}/lib/libclang.so /usr/lib/x86_64-linux-gnu/libclang-12.so
          sudo apt-get update
          sudo apt install libtinfo5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.3"
          enable-cache: true
          cache-suffix: ${{ matrix.sphinx-version }}
      - name: Test with tox
        run: |
          uv run --locked tox -e sphinx-${{ matrix.sphinx-version }}
